volumes:
  venv_cache:

services:

  postgres:
    image: postgres:latest
    container_name: pg
    networks:
      - booking_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: cache
    networks:
      - booking_network
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  booking_back_service:
    container_name: booking_back
    networks:
      - booking_network
    build:
      context: .
    ports:
      - '8000:8000'
    env_file:
      - .env-docker-compose
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python src/main.py


  booking_celery_worker_service:
    container_name: booking_celery_worker
    networks:
      - booking_network
    build:
      context: .
    command: celery -A src.tasks.celery_app:celery_instance worker -l INFO
    env_file:
      - .env-docker-compose
    depends_on:
      - redis

  booking_celery_beat_service:
    container_name: booking_celery_beat
    networks:
      - booking_network
    build:
      context: .
    command: celery -A src.tasks.celery_app:celery_instance beat -l INFO
    env_file:
      - .env-docker-compose
    depends_on:
      - redis

networks:
  booking_network: